### ISSUE TITLE
[Question] Pi-hole on one Raspberry, Homebridge on another

### ISSUE THREAD

**Issue by DJay-X** [MrDrache333/homebridge-pihole#1]
Hi. I hope you can help.
When I install cmd4 on my Homebridge RPi, can I use this and how, to switch on/of Pi-hole on another RPi an also get the real status?
Thanks in advance for the help.

**Comment by MrDrache333** [comment]
Yes you can. You can generate an ssh Key on the other Raspi and Copy it to this raspi.
then you can simply edit the Command, by putting the ssh command before it.

Pi1 = Raspi with Homebridge
Pi2 = Raspi with PiHole

Try the following and Replace everything in ** with your Data:
Pi2: 
`sudo ssh-keygen` Generate a SSH Public Key, to login without password; store it wherever you want
`scp *path to generated Key-File* *userofPi1*@*IPofPi1*:/home/*UserOfPi1*` Copy this File to your Main Raspi

Pi1:
`cd /home/*UserOfPi1*`
`mv *NameOfKeyFile* .ssh/` Copy the Key to the known Keys

Add the Following to the piHole.sh Script:

Before every `piHole status/ enable or disable` put `ssh *UserOfPi2*@*IPofPi2*`

For Example:
`ssh pi@192.168.178.123 pihole status`

Hope this helps 😃
