### ISSUE TITLE
Unable to execute switch

### ISSUE THREAD

**Issue by ghost** [MrDrache333/homebridge-pihole#2]
Hi,

I just installed cmd4 and tried to use your script, with no success..

My homebridge ist at /var/homebridge/ so I created there a new folder cmd4

I then copied the pihole.sh file into that folder, I added the config.json part, but I had to change two minor things:

{
            "platform": "Cmd4",
            "name": "Cmd4",
            "accessories": [
                {
                    "type": "Switch",
                    "name": "PiHole",
                    "on": false,
                    "state_cmd": "bash **/var/homebridge/**cmd4/pihole.sh"**,**
                    "polling": true,
                    "interval": 5,
                    "timeout": 2000
                }
            ]
        },

I marked my change in bold and additionally I had to remove the last comma after 2000, otherwise it would not let me save the config and jsonlint also says, somewthing is wrong, as long as I do not change these things. 

I have now the switch visible in my Home App, but it says not responding. How can I fix that issue? the homebridge logs tells me: 

Apr 06 01:23:19 raspberrypi homebridge[5854]: [2019-4-6 01:23:19] [Cmd4] Cmd4 getGeneric On function for: PiHole cmd: bash /var/homebridge/cmd4/pihole.sh Get 'PiHole' 'On' failed.
Apr 06 01:23:19 raspberrypi homebridge[5854]: [2019-4-6 01:23:19] [Cmd4] { Error: Command failed: bash /var/homebridge/cmd4/pihole.sh Get 'PiHole' 'On'
Apr 06 01:23:19 raspberrypi homebridge[5854]: /var/homebridge/cmd4/pihole.sh: Zeile 7: Syntaxfehler beim unerwarteten Wort `newline'
Apr 06 01:23:19 raspberrypi homebridge[5854]: /var/homebridge/cmd4/pihole.sh: Zeile 7: `<!DOCTYPE html>'
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at ChildProcess.exithandler (child_process.js:281:12)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at emitTwo (events.js:126:13)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at ChildProcess.emit (events.js:214:7)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at maybeClose (internal/child_process.js:915:16)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at Socket.stream.socket.on (internal/child_process.js:336:11)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at emitOne (events.js:116:13)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at Socket.emit (events.js:211:7)
Apr 06 01:23:19 raspberrypi homebridge[5854]:     at Pipe._handle.close [as _onclose] (net.js:561:12)
Apr 06 01:23:19 raspberrypi homebridge[5854]:   killed: false,
Apr 06 01:23:19 raspberrypi homebridge[5854]:   code: 2,
Apr 06 01:23:19 raspberrypi homebridge[5854]:   signal: null,
Apr 06 01:23:19 raspberrypi homebridge[5854]:   cmd: 'bash /var/homebridge/cmd4/pihole.sh Get \'PiHole\' \'On\'' }
Apr 06 01:23:19 raspberrypi homebridge[5854]: [2019-4-6 01:23:19] [Cmd4]
Apr 06 01:23:19 raspberrypi homebridge[5854]: [2019-4-6 01:23:19] [Cmd4] /var/homebridge/cmd4/pihole.sh: Zeile 7: Syntaxfehler beim unerwarteten Wort `newline'
Apr 06 01:23:19 raspberrypi homebridge[5854]: /var/homebridge/cmd4/pihole.sh: Zeile 7: `<!DOCTYPE html>'

Thx in advance for any help!

**Comment by MrDrache333** [comment]
It seems that in your Script is something wrong...can you please Post it? The Error seems t one in Line 7

`/var/homebridge/cmd4/pihole.sh: Zeile 7: Syntaxfehler beim unerwarteten Wort newline Apr 06 01:23:19 raspberrypi homebridge[5854]: /var/homebridge/cmd4/pihole.sh: Zeile 7: `
